# Generated by Django 6.0.4 on 2026-05-17 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dailypick_paperholding_paperportfolio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("UP", "Up"), ("DOWN", "Down")], max_length=4
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("3D", "3 Days"),
                            ("1W", "1 Week"),
                            ("2W", "2 Weeks"),
                            ("1M", "1 Month"),
                        ],
                        max_length=2,
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("resolves_at", models.DateField()),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=7,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                        ],
                        default="PENDING",
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parlays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParlayLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("UP", "Up"), ("DOWN", "Down")], max_length=4
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=7,
                    ),
                ),
                (
                    "parlay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="core.parlay",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("streak", models.IntegerField(default=0)),
                ("total_picks", models.IntegerField(default=0)),
                ("total_wins", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
