# Generated by Django 6.0.4 on 2026-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
