# Generated by Django 6.0.4 on 2026-06-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_userprofile_bio_userprofile_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BullishPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=100)),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("UP", "Up"), ("DOWN", "Down")], max_length=4
                    ),
                ),
                ("reasoning", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "momentum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(unique=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
