# Generated by Django 6.0.4 on 2026-06-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_portfolio_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_seen_tour",
            field=models.BooleanField(default=False),
        ),
    ]
